version: '3'
services:
  mysqldb:
    image: mysql:8
    restart: always
    volumes:
      - ./Schema:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app-deadline
#      - MYSQL=localhost:3306/app-deadline
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass